### ISSUE TITLE
sinatra dependency

### ISSUE THREAD

**Issue by mynyml** [cehoffman/sinatra-respond_to#1]
gem is dependent on sinatra >= 0.9.1.3, which is the github sinatra gem (regular gem is still at v0.9.1.1). Problem is the github gem is called sinatra-sinatra.

<pre>
~/dev/projects/api| gem list .*sinatra

*** LOCAL GEMS ***

sinatra (0.9.1.1)
sinatra-sinatra (0.9.1.3)
~/dev/projects/api| sudo gem install cehoffman-sinatra-respond_to
ERROR:  Error installing cehoffman-sinatra-respond_to:
    cehoffman-sinatra-respond_to requires sinatra (>= 0.9.1.3, runtime)
</pre>

**Comment by cehoffman** [comment]
Ah thanks, that caught a bug I had with two sinatra versions on my system.  I got it sorted out and worked around the classic application problem.
