### ISSUE TITLE
NoMethodError for sinatra-respond_to 0.5.0 and sinatra 1.1.0

### ISSUE THREAD

**Issue by jmettraux** [cehoffman/sinatra-respond_to#3]
app.rb, Gemfile and stacktrace.txt at :

  http://gist.github.com/644773

observed with ruby 1.8.7-p299 and 1.9.1-p0 on OSX Snow Leopard

Many thanks for sinatra-respond_to

**Comment by cehoffman** [comment]
Thanks for reporting this, I'll look into it later today.

**Comment by ashaw** [comment]
I fixed this here: http://github.com/ashaw/sinatra-respond_to/commit/1bcb067356ce1fcac442fb1667a6389e2abf0f0b

**Comment by cehoffman** [comment]
Based on the changes from ashaw I looked more closely at the changes between Sinatra 1.0 and 1.1 and decided a new version should be released that was meant for Sinatra 1.1.

The main reason is that Sinatra now has a setting for default_charset called default_encoding and I should really encourage people to use that over my methods, although I still provide the helper for setting the charset independently of the format.

Also of note is that 1.1 supports automatically setting the content type based on the render used, however that happens at the end of the request cycle which isn't helpful when deciding which block of the respond_to should run.

Try using version 0.6.0, that should resolve the problem.

**Comment by jmettraux** [comment]
0.6.0 works great for me.

Many thanks for the rapid fix.

**Comment by jmettraux** [comment]
Chris, when will you release 0.6.0 ?

https://rubygems.org/gems/sinatra-respond_to

Thanks again

**Comment by cehoffman** [comment]
Wow, I don't know what happened there. But it should have been pushed to the rubygem servers when I tagged the release. It should be out there now.

**Comment by jmettraux** [comment]
Yes, 0.6.0 is out. Thanks for the fast answer !
