### ISSUE TITLE
respond_to recursively calls itself

### ISSUE THREAD

**Issue by ajsharp** [cehoffman/sinatra-respond_to#9]
We're using 0.7.0. We have a sinatra app being mounted in a rails 3 router, but we have seen this behavior outside of rails.
Basically, the library goes into an infinite loop, trying to calling the aliased method until ruby throws a stack level too deep error. Here's where things blow up, in `respond_to.rb` on line 157:

``` ruby
    module Helpers
      # Patch the content_type function to remember the set type
      # This helps cut down on time in the format helper so it
      # doesn't have to do a reverse lookup on the header
      def self.included(klass)
        klass.class_eval do
          alias :content_type_without_save :content_type
          def content_type(*args)
            @_format = (args.first ? args.first.to_sym : nil)
            content_type_without_save *args
          end
        end
      end

```

**Comment by ajsharp** [comment]
After trying to implement a simpler version of this myself, I think I've found what the problem is -- code reloading: http://blog.jayfields.com/2008/04/alternatives-for-redefining-methods.html. I code gets reloaded twice in rails on the initial bootstrap pass, and something similar must happen with Padrino as well (previously, we were running a sinatra app alongside a padrino app). I'm going to continue to investigate and see if I can come up with a solution.

**Comment by cehoffman** [comment]
The new release should have this fixed. Thanks for bugging me over and over :)
